### ISSUE TITLE
Does not render diagram when used with mkdocstrings

### ISSUE THREAD

**Issue by butterlyn** [AVATEAM-IT-SYSTEMHAUS/mkdocs-kroki-plugin#78]
Kroki diagrams within Python docstrings, parsed with mkdocstrings, do not render. Currently, the only way to render kroki diagrams is with `.md` files, not `.py` files.

Please see reference to mkdocstrings recipe:
https://mkdocstrings.github.io/recipes/

**Comment by pawamoy** [comment]
That's probably because this plugin operates on Markdown, and mkdocstrings does not generate Markdown or pass anything to other plugins, so this plugin never gets to see docstrings and operate on it. mkdocstrings works at the Markdown-to-HTML conversion layer.

There are two ways to make this work: rewrite this plugin as a Markdown extension, or hack into mkdocstrings' internals. I'll try t share a link that explains this later.

**Comment by oniboni** [comment]
Yep, nothing we can do here.

I'm closing this one.
